const locations={chamoli:{name:"Chamoli, Uttarakhand",coords:"30.41° N, 79.32° E",lat:30.41,lng:79.32},shimla:{name:"Shimla, Himachal Pradesh",coords:"31.10° N, 77.17° E",lat:31.10,lng:77.17},tehri:{name:"Tehri, Uttarakhand",coords:"30.38° N, 78.48° E",lat:30.38,lng:78.48},itanagar:{name:"Itanagar, Arunachal Pradesh",coords:"27.08° N, 93.62° E",lat:27.08,lng:93.62}};
const map=L.map("map",{zoomControl:true}).setView([29.8,82.4],5.7);
const satellite=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxZoom:18,attribution:"Tiles © Esri"}).addTo(map);
const terrain=L.tileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",{maxZoom:17,attribution:"© OpenTopoMap contributors"});
const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"});
const stormAreas=[[[30.25,78.9],[30.8,79.1],[30.65,79.65],[30.1,79.5]],[[28.0,93.0],[27.7,93.8],[27.2,93.55],[27.45,92.8]],[[27.7,87.4],[28.2,87.8],[28.0,88.4],[27.5,88.0]]];
stormAreas.forEach(function(points,i){L.polygon(points,{color:"transparent",fillColor:i===0?"#f36b32":"#f4c23e",fillOpacity:.28,weight:0}).addTo(map)});
const labelData=[["JAMMU & KASHMIR",34.2,75.3],["LADAKH",34.3,78.1],["HIMACHAL\nPRADESH",31.8,77.2],["PUNJAB",31.0,75.3],["HARYANA",29.2,76.0],["DELHI",28.6,77.2],["RAJASTHAN",27.2,73.8],["UTTAR PRADESH",27.3,80.6],["UTTARAKHAND",30.2,79.3],["BIHAR",25.8,85.3],["SIKKIM",27.5,88.5],["ARUNACHAL\nPRADESH",28.5,94.0],["ASSAM",26.1,92.6],["NAGALAND",26.2,94.4],["MANIPUR",24.9,93.8],["MEGHALAYA",25.6,91.4]];
labelData.forEach(function(x){L.marker([x[1],x[2]],{interactive:false,icon:L.divIcon({className:"map-state-label",html:x[0].replace("\n","<br>"),iconSize:[100,30],iconAnchor:[50,15]})}).addTo(map)});
const marker=L.marker([locations.chamoli.lat,locations.chamoli.lng]).addTo(map);
function selectLocation(key){const x=locations[key];if(!x)return;document.getElementById("selectedLocation").textContent=x.name;document.getElementById("coordinates").textContent=x.coords;map.flyTo([x.lat,x.lng],8,{duration:1});marker.setLatLng([x.lat,x.lng])}
document.getElementById("searchBtn").onclick=function(){const q=document.getElementById("locationSearch").value.toLowerCase();const key=Object.keys(locations).find(function(k){return q.includes(k)});if(key)selectLocation(key)};
document.getElementById("locationSearch").addEventListener("keydown",function(e){if(e.key==="Enter")document.getElementById("searchBtn").click()});
document.querySelectorAll(".tab").forEach(function(btn){btn.onclick=function(){document.querySelectorAll(".tab").forEach(function(b){b.classList.remove("active")});btn.classList.add("active");const mode=btn.dataset.mode;if(mode==="nowcast"||mode==="satellite"){if(!map.hasLayer(satellite))map.addLayer(satellite);if(map.hasLayer(terrain))map.removeLayer(terrain);if(map.hasLayer(street))map.removeLayer(street)}else{if(!map.hasLayer(street))map.addLayer(street);if(map.hasLayer(satellite))map.removeLayer(satellite);if(map.hasLayer(terrain))map.removeLayer(terrain)}}});
const forecast=[["02:30 – 03:30 PM","🌧️","Low","low"],["03:30 – 04:30 PM","⛈️","Moderate","moderate"],["04:30 – 05:30 PM","⛈️","High","high"],["05:30 – 06:30 PM","🌧️","High","high"],["06:30 – 07:30 PM","🌧️","Moderate","moderate"],["07:30 – 08:30 PM","☁️","Low","low"]];
document.getElementById("forecastGrid").innerHTML=forecast.map(function(x){return '<div class="forecast-item"><div class="time">'+x[0]+'</div><div class="wx">'+x[1]+'</div><span class="level '+x[3]+'">'+x[2]+'</span></div>'}).join("");
const initialLocation=new URLSearchParams(window.location.search).get("location");if(initialLocation&&locations[initialLocation])selectLocation(initialLocation);