"""Initial SkyIntel PostGIS schema."""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
    op.create_table("locations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("slug",sa.String(100),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("state",sa.String(100)),sa.Column("latitude",sa.Float(),nullable=False),sa.Column("longitude",sa.Float(),nullable=False),sa.Column("geom",Geometry("POINT",srid=4326)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_locations_slug","locations",["slug"],unique=True)
    op.create_table("ingestion_runs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("provider",sa.String(100),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("records_written",sa.Integer(),server_default="0",nullable=False),sa.Column("location_slug",sa.String(100)),sa.Column("raw_object_key",sa.Text()),sa.Column("error",sa.Text()),sa.Column("metadata_json",sa.JSON(),nullable=False));op.create_index("ix_ingestion_runs_provider","ingestion_runs",["provider"]);op.create_index("ix_ingestion_runs_status","ingestion_runs",["status"])
    op.create_table("weather_observations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("location_id",sa.Integer(),sa.ForeignKey("locations.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(100),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.Column("temperature_c",sa.Float()),sa.Column("humidity_pct",sa.Float()),sa.Column("precipitation_probability_pct",sa.Float()),sa.Column("precipitation_mm",sa.Float()),sa.Column("rain_mm",sa.Float()),sa.Column("showers_mm",sa.Float()),sa.Column("cloud_cover_pct",sa.Float()),sa.Column("cloud_cover_low_pct",sa.Float()),sa.Column("cloud_cover_mid_pct",sa.Float()),sa.Column("cloud_cover_high_pct",sa.Float()),sa.Column("wind_speed_kmh",sa.Float()),sa.Column("wind_direction_deg",sa.Float()),sa.Column("wind_gust_kmh",sa.Float()),sa.Column("weather_code",sa.Integer()),sa.Column("quality_flags",sa.JSON(),nullable=False),sa.Column("raw_object_key",sa.Text()),sa.Column("payload",sa.JSON(),nullable=False),sa.UniqueConstraint("location_id","provider","observed_at",name="uq_weather_observation_source_time"));op.create_index("ix_weather_provider_time","weather_observations",["provider","observed_at"])
    op.create_table("predictions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("location_id",sa.Integer(),sa.ForeignKey("locations.id",ondelete="CASCADE"),nullable=False),sa.Column("hazard",sa.String(32),nullable=False),sa.Column("score",sa.Float(),nullable=False),sa.Column("score_type",sa.String(40),nullable=False),sa.Column("risk_band",sa.String(32),nullable=False),sa.Column("forecast_hour",sa.Integer(),nullable=False),sa.Column("issued_at",sa.DateTime(timezone=True),nullable=False),sa.Column("valid_at",sa.DateTime(timezone=True),nullable=False),sa.Column("model_version",sa.String(128),nullable=False),sa.Column("uncertainty",sa.Float()),sa.Column("feature_snapshot",sa.JSON(),nullable=False),sa.Column("warnings",sa.JSON(),nullable=False));op.create_index("ix_predictions_hazard","predictions",["hazard"]);op.create_index("ix_predictions_issued_at","predictions",["issued_at"]);op.create_index("ix_predictions_valid_at","predictions",["valid_at"])
    op.create_table("model_registry",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("hazard",sa.String(32),nullable=False),sa.Column("version",sa.String(128),nullable=False),sa.Column("artifact_path",sa.Text(),nullable=False),sa.Column("checksum_sha256",sa.String(64)),sa.Column("feature_names",sa.JSON(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("calibration",sa.JSON(),nullable=False),sa.Column("training_period",sa.JSON(),nullable=False),sa.Column("approved",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False));op.create_index("ix_model_registry_hazard","model_registry",["hazard"]);op.create_index("ix_model_registry_version","model_registry",["version"])
def downgrade():
    for t in ["model_registry","predictions","weather_observations","ingestion_runs","locations"]:op.drop_table(t)
