from datetime import datetime
from typing import Any
from sqlalchemy import DateTime,ForeignKey,Index,JSON,Float,Integer,String,Text,UniqueConstraint
from sqlalchemy.orm import DeclarativeBase,Mapped,mapped_column,relationship
from geoalchemy2 import Geometry
class Base(DeclarativeBase):pass
class Location(Base):
    __tablename__="locations";id:Mapped[int]=mapped_column(primary_key=True);slug:Mapped[str]=mapped_column(String(100),unique=True,index=True);name:Mapped[str]=mapped_column(String(200));state:Mapped[str|None]=mapped_column(String(100));latitude:Mapped[float]=mapped_column(Float);longitude:Mapped[float]=mapped_column(Float);geom:Mapped[Any|None]=mapped_column(Geometry("POINT",srid=4326));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class IngestionRun(Base):
    __tablename__="ingestion_runs";id:Mapped[int]=mapped_column(primary_key=True);provider:Mapped[str]=mapped_column(String(100),index=True);status:Mapped[str]=mapped_column(String(32),index=True);started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow);finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));records_written:Mapped[int]=mapped_column(Integer,default=0);location_slug:Mapped[str|None]=mapped_column(String(100));raw_object_key:Mapped[str|None]=mapped_column(Text);error:Mapped[str|None]=mapped_column(Text);metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class WeatherObservation(Base):
    __tablename__="weather_observations";id:Mapped[int]=mapped_column(primary_key=True);location_id:Mapped[int]=mapped_column(ForeignKey("locations.id",ondelete="CASCADE"),index=True);provider:Mapped[str]=mapped_column(String(100),index=True);observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow);temperature_c:Mapped[float|None]=mapped_column(Float);humidity_pct:Mapped[float|None]=mapped_column(Float);precipitation_probability_pct:Mapped[float|None]=mapped_column(Float);precipitation_mm:Mapped[float|None]=mapped_column(Float);rain_mm:Mapped[float|None]=mapped_column(Float);showers_mm:Mapped[float|None]=mapped_column(Float);cloud_cover_pct:Mapped[float|None]=mapped_column(Float);cloud_cover_low_pct:Mapped[float|None]=mapped_column(Float);cloud_cover_mid_pct:Mapped[float|None]=mapped_column(Float);cloud_cover_high_pct:Mapped[float|None]=mapped_column(Float);wind_speed_kmh:Mapped[float|None]=mapped_column(Float);wind_direction_deg:Mapped[float|None]=mapped_column(Float);wind_gust_kmh:Mapped[float|None]=mapped_column(Float);weather_code:Mapped[int|None]=mapped_column(Integer);quality_flags:Mapped[list]=mapped_column(JSON,default=list);raw_object_key:Mapped[str|None]=mapped_column(Text);payload:Mapped[dict]=mapped_column(JSON,default=dict)
    __table_args__=(UniqueConstraint("location_id","provider","observed_at",name="uq_weather_observation_source_time"),Index("ix_weather_provider_time","provider","observed_at"))
class Prediction(Base):
    __tablename__="predictions";id:Mapped[int]=mapped_column(primary_key=True);location_id:Mapped[int]=mapped_column(ForeignKey("locations.id",ondelete="CASCADE"),index=True);hazard:Mapped[str]=mapped_column(String(32),index=True);score:Mapped[float]=mapped_column(Float);score_type:Mapped[str]=mapped_column(String(40));risk_band:Mapped[str]=mapped_column(String(32),index=True);forecast_hour:Mapped[int]=mapped_column(Integer);issued_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);valid_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),index=True);model_version:Mapped[str]=mapped_column(String(128));uncertainty:Mapped[float|None]=mapped_column(Float);feature_snapshot:Mapped[dict]=mapped_column(JSON,default=dict);warnings:Mapped[list]=mapped_column(JSON,default=list)
class ModelRegistry(Base):
    __tablename__="model_registry";id:Mapped[int]=mapped_column(primary_key=True);hazard:Mapped[str]=mapped_column(String(32),index=True);version:Mapped[str]=mapped_column(String(128),index=True);artifact_path:Mapped[str]=mapped_column(Text);checksum_sha256:Mapped[str|None]=mapped_column(String(64));feature_names:Mapped[list]=mapped_column(JSON,default=list);metrics:Mapped[dict]=mapped_column(JSON,default=dict);calibration:Mapped[dict]=mapped_column(JSON,default=dict);training_period:Mapped[dict]=mapped_column(JSON,default=dict);approved:Mapped[bool]=mapped_column(default=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
